# Generated by Django 4.1.6 on 2023-10-09 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_api', '0002_product_providerid'),
        ('deliverylocations_api', '0002_deliverylocations_deliveryzoneid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirationDate', models.DateField()),
                ('quantityDelivered', models.IntegerField()),
                ('quantityReturned', models.IntegerField(blank=True, null=True)),
                ('soldPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('deliveryDate', models.DateField()),
                ('deliveryLocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverylocations_api.deliverylocations')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_api.product')),
            ],
        ),
    ]
