# Generated by Django 4.1.8 on 2023-05-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdelivery_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdelivery',
            name='quantityReturned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
