# Generated by Django 4.1.6 on 2023-07-17 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productdelivery_api', '0002_alter_productdelivery_quantityreturned'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdelivery',
            name='deliveryDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
