# Generated by Django 4.1.6 on 2023-07-17 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryzones_api', '0001_initial'),
        ('deliverylocations_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylocations',
            name='deliveryZoneId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='deliveryzones_api.deliveryzones'),
            preserve_default=False,
        ),
    ]
