# Generated by Django 4.2.2 on 2023-08-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('user', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
    ]
