# Generated by Django 4.1.6 on 2023-04-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
