# Generated by Django 4.1.6 on 2023-07-17 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers_api', '0001_initial'),
        ('products_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='providerId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='providers_api.providers'),
            preserve_default=False,
        ),
    ]
